name: flutterfinalproje
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  anim_search_bar: ^2.0.3
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  credit_card_form: ^0.0.7
  flex_color_scheme: ^7.3.1
  flutter_bloc: ^8.1.5
  flutter_svg: ^2.0.9
  flutter_credit_card: ^4.0.1
  flutter_localization: ^0.2.0
  google_nav_bar: ^5.0.6
  gap: ^3.0.1
  go_router: ^14.0.2
  image_picker: ^1.0.7
  preload_page_view: ^0.2.0
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  permission_handler: ^11.3.1
  dio: ^5.4.2+1
  animated_text_kit: ^4.2.2
  flutter_secure_storage : ^ 9.0.0
  path_provider: ^2.1.3

 
  

  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/fonts/
    - assets/images/
    - assets/images/achievements/
    - assets/images/carouselslider/
    - assets/images/login/
    - assets/images/register/
    - assets/images/routes/
    - assets/images/profile/
    - assets/images/places/
    - assets/images/cards/
    - assets/images/photographs/
    - assets/lang/
    - assets/chatbot/
    - assets/images/boarding/
    - assets/images/logo/
    - assets/images/thememodescreen/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf